const configData = {
 "memSavingMethod": 1,
 "mainConfig": {
  "description": {
   "simple": "<div id=\"title\">missieven-text search</div>",
   "full": "<details id=\"titledetails\">\n  <summary id=\"title\">missieven-text search</summary>\n  <div id=\"description\"></div>\n  <a\n     id=\"makerlink\" href=\"#\"\n     class=\"logo right\"\n  ><img alt=\"maker logo\" id=\"logo\" src=\"png/maker.png\"></a>\n  <a\n     id=\"tflink\" href=\"#\"\n     class=\"logo right\"\n  ><img alt=\"Text-Fabric logo\" id=\"logo\" src=\"png/tf.png\"></a>\n  <details>\n    <summary><i>open source</i></summary>\n    <div>\n      <p>You can\n      <a id=\"packagelink\" href=\"#\"></a>\n      this web page and use it offline\n      by unzipping and double clicking <i>text-local.html</i>.\n      </p>\n      <p>This app is generated by <a id=\"generatorlink\" href=\"#\"></a>\n      based on a configuration in <a id=\"sourcelink\" href=\"#\"></a>.\n      </p>\n      <p>Written by: <a id=\"authorlink\" href=\"#\" ></a>.\n      <p>License: <a id=\"licenselink\" href=\"#\" ></a>\n      (you are free to use and modify the code).\n      </p>\n    </div>\n  </details>\n</details>"
  },
  "jobs": {
   "simple": "",
   "full": "<div id=\"jobs\">\n  <input\n    type=\"file\" name=\"imjname\" id=\"imjname\"\n    accept=\"application/json\"\n    class=\"import\"\n  >\n  <button\n    type=\"button\" class=\"medium active\" id=\"importj\"\n    title=\"import job from file\"\n  >↑</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"deletej\"\n    title=\"delete current job\"\n  >-</button>\n  <select class=\"selinp\" id=\"jchange\"></select>\n  <button\n    type=\"button\" class=\"medium active\" id=\"newj\"\n    title=\"fresh new job\"\n  >+</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"renamej\"\n    title=\"rename current job\"\n  >→</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"dupj\"\n    title=\"duplicate current job\"\n  >++</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"exportj\"\n    title=\"export job to file\"\n  >↓</button>\n</div>"
  },
  "provenance": {
   "simple": "<table>\n  <tbody>\n    <tr>\n      <td>help</td>\n      <td><a id=\"lsdocsimplelink\" href=\"#\"></a></td>\n    </tr>\n    <tr>\n      <td>data version</td>\n      <td><a id=\"datalink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>app version</td>\n      <td><span id=\"appversion\"></span></td>\n    </tr>\n  </tbody>\n</table>",
   "full": "<table>\n  <tbody>\n    <tr>\n      <td>help</td>\n      <td><a id=\"lsdoclink\" href=\"#\"></a> ; <a id=\"cheatsheetlink\" href=\"#\"></a></td>\n    </tr>\n    <tr>\n      <td>writing</td>\n      <td><a id=\"writinglink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>docs</td>\n      <td><a id=\"datadoclink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>related</td>\n      <td><a id=\"relatedlink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>data version</td>\n      <td><a id=\"datalink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>app version</td>\n      <td><span id=\"appversion\"></span></td>\n    </tr>\n  </tbody>\n</table> <p><a id=\"issuelink\" href=\"#\" class=\"medium active\"></a>\n  please copy the version above this line\n</p>"
  }
 },
 "defs": {
  "lsVersion": "v078@2021-06-14T11:33:17",
  "dataset": "missieven",
  "client": "text",
  "org": "annotation",
  "repo": "app-missieven",
  "urls": {
   "cheatsheet": [
    "regexp cheatsheet",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet",
    "cheatsheet of regular expressions"
   ],
   "license": [
    "MIT",
    "https://mit-license.org",
    "website of MIT license"
   ],
   "maker": [
    null,
    "https://dans.knaw.nl/en/front-page?set_language=en",
    "Website of DANS = Data Archiving and Networked Services"
   ],
   "corpus": [
    null,
    "http://resources.huygens.knaw.nl/retroboeken/generalemissiven/#page=0&accessor=toc&view=homePane",
    "Huygens-ING portal to Missieven"
   ],
   "corpus2": [
    "General Missives",
    "http://resources.huygens.knaw.nl/retroboeken/generalemissiven/#page=0&accessor=toc&view=homePane",
    "Huygens-ING portal to Missieven"
   ],
   "author": [
    "Dirk Roorda",
    "https://pure.knaw.nl/portal/en/persons/dirk-roorda",
    "profile of the author"
   ],
   "author1": [
    "Lodewijk Petram",
    "http://resources.huygens.knaw.nl/retroboeken/generalemissiven/#page=0&accessor=toc&view=homePane",
    "lead researcher"
   ],
   "author2": [
    "Dirk Roorda",
    "https://pure.knaw.nl/portal/en/persons/dirk-roorda",
    "data modeler"
   ],
   "tf": [
    null,
    "https://annotation.github.io/text-fabric/tf/",
    "Text-Fabric documentation website"
   ],
   "lsdoc": [
    "user manual (full)",
    "https://annotation.github.io/text-fabric/tf/about/clientmanual.html",
    "user manual for the full search interface"
   ],
   "lsdocsimple": [
    "user manual (simple)",
    "https://annotation.github.io/text-fabric/tf/about/manual.html",
    "user manual for the simplified search interface"
   ],
   "datadoc": [
    "data (feature) documentation",
    "https://github.com/Dans-labs/clariah-gm/blob/master/docs/transcription.md",
    "explanation of the features in the dataset"
   ],
   "data": [
    "based on text-fabric data version 0.8",
    "https://github.com/Dans-labs/clariah-gm/tree/master/tf/0.8",
    "online repository of the underlying text-fabric data"
   ],
   "generator": [
    "text-fabric/client",
    "https://annotation.github.io/text-fabric/tf/client/make/build.html",
    "the generator of this search interface"
   ],
   "source": [
    "app-missieven",
    "https://github.com/annotation/app-missieven/tree/master/layeredsearch",
    "source code of the definition of this search interface"
   ],
   "issue": [
    "Report an issue",
    "https://github.com/annotation/app-missieven/issues",
    "report issues"
   ],
   "package": [
    "download",
    "../text.zip",
    "zip file for offline use"
   ],
   "writing": [
    "",
    "https://annotation.github.io/text-fabric/tf/writing/.html",
    "characters and transliteration for "
   ],
   "related": [
    "text-fabric missieven",
    "https://nbviewer.jupyter.org/github/annotation/tutorials/tree/master/missieven/start.ipynb",
    "using Text-Fabric on the same corpus"
   ]
  },
  "description": "<p>Text-kind aware full-text search in <a id=\"corpus2link\" href=\"#\"></a>.</p> <p>This search interface is by:</p> <ul>\n    <li><a id=\"author2link\" href=\"#\"></a> (data modeler)\n    <li><a id=\"author1link\" href=\"#\"></a> (lead researcher)\n</ul>"
 },
 "ntypes": [
  "word",
  "line",
  "letter",
  "volume"
 ],
 "typesLower": {
  "word": [
   "word"
  ],
  "line": [
   "word",
   "line"
  ],
  "letter": [
   "word",
   "line",
   "letter"
  ],
  "volume": [
   "word",
   "line",
   "letter",
   "volume"
  ]
 },
 "defaultSettings": {
  "autoexec": true,
  "nodeseq": true,
  "exporthl": true,
  "exportsr": true,
  "multihl": true,
  "simple": false
 },
 "defaultFlags": {
  "i": true,
  "m": true,
  "s": false
 },
 "keyboard": {
  "’": "apostrophe",
  "‘": "inverted single quote",
  "“": "inverted double quote",
  "„": "opening double quote",
  "”": "closing double quote",
  "¬": "symbol",
  "—": "em-dash",
  "■": "square bullet",
  "°": "degree",
  "ƒ": "florin",
  "®": "registered",
  "™": "trademark",
  "©": "copyright",
  "•": "bullet",
  "≤": "less than or equal",
  "≥": "greater than or equal",
  "∪": "union",
  "Ö": "O-trema",
  "Ê": "E-trema",
  "♦": "diamond",
  "►": "triangle",
  "⌊": "hook bottom left",
  "⌋": "hook bottom right"
 },
 "focusType": "line",
 "ntypesinit": {
  "word": 1,
  "line": 5340163,
  "letter": 5339574,
  "volume": 5891019
 },
 "ntypessize": {
  "word": 5316429,
  "line": 465366,
  "letter": 589,
  "volume": 13
 },
 "dtypeOf": {
  "line": "word",
  "letter": "line",
  "volume": "letter"
 },
 "utypeOf": {
  "word": "line",
  "line": "letter",
  "letter": "volume"
 },
 "visible": {
  "word": {
   "text": true,
   "kind": true
  },
  "line": {
   "location": false
  },
  "letter": {
   "page": false,
   "author": true,
   "date": true,
   "place": true
  },
  "volume": {
   "number": false
  }
 },
 "levels": {
  "word": "words (some words do not have a space between them)",
  "line": "physical lines in the printed edition",
  "letter": "missives (i.e. letters)",
  "volume": "physical volume in the printed edition"
 },
 "layers": {
  "word": {
   "text": {
    "valueMap": null,
    "tip": false,
    "pos": "text",
    "pattern": "",
    "description": "text representation"
   },
   "kind": {
    "valueMap": [
     [
      "?",
      113187
     ],
     [
      "f",
      8730
     ],
     [
      "n",
      204959
     ],
     [
      "o",
      3260840
     ],
     [
      "r",
      1728713
     ]
    ],
    "tip": false,
    "pos": "kind",
    "pattern": "",
    "description": "text kind"
   }
  },
  "line": {
   "location": {
    "valueMap": null,
    "tip": false,
    "pos": "location",
    "pattern": "",
    "description": "page number:line number within the page"
   }
  },
  "letter": {
   "page": {
    "valueMap": null,
    "tip": false,
    "pos": "page",
    "pattern": "",
    "description": "starting page number within the book"
   },
   "author": {
    "valueMap": [
     [
      "Abraham Patras, Wijbrant Blom, Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne",
      5
     ],
     [
      "Abraham Patras, Wijbrant Blom, Herman van Bayen, Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen",
      2
     ],
     [
      "Abraham Patras, Wijbrant Blom, Herman van Bayen, Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes",
      1
     ],
     [
      "Abraham Patras, Wijbrant Blom, Herman van Bayen, Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Joannes Bernard, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen",
      2
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Cornelis Chasteleyn, Mattheus de Haan, Frans Castelyn, Hendrik Zwaardecroon, Pieter Rooselaar, Theodorus de Haeze, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      1
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Cornelis Chasteleyn, Mattheus de Haan, Frans Castelyn, Laurens Tolling, Hendrik Zwaardecroon, Pieter Rooselaar, Theodorus de Haeze, Joannes van Steelant, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      2
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Cornelis Chasteleyn, Mattheus de Haan, Frans Castelyn, Laurens Tolling, Hendrik Zwaardecroon, Pieter Rooselaar, Theodorus de Haeze, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      3
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Cornelis Chasteleyn, Mattheus de Haan, Laurens Tolling, Hendrik Zwaardecroon, Pieter Rooselaar, Theodorus de Haeze, Frans Castelyn, Joannes van Steelant, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      1
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Cornelis Chasteleyn, Mattheus de Haan, Laurens Tolling, Hendrik Zwaardecroon, Theodorus de Haeze, Frans Castelyn, Joannes van Steelant, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      1
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Pieter de Vos, Cornelis Chasteleyn, Hendrick Zwaardecroon, Mattheus de Haan, Theodorus de Haeze, Laurens Tolling, Frans Castelyn",
      1
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Pieter de Vos, Cornelis Chasteleyn, Hendrick Zwaardecroon, Pieter Rooselaar, Mattheus de Haan, Theodorus de Haeze, Laurens Tolling, Frans Castelyn",
      2
     ],
     [
      "Abraham van Riebeeck, Abraham Douglas, Christoffel van Swoll, Pieter de Vos, Cornelis Chasteleyn, Mattheus de Haan, Laurens Tolling, Hendrik Zwaardecroon, Pieter Rooselaar, Theodorus de Haeze, Frans Castelyn, Joannes van Steelant, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Gualterus Wouters",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot",
      2
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius, Nicolaas van Berendregt",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius",
      2
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Gualterus Wouters, Elias Guillot",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Gualterus Wouters, Joannes Sautijn",
      3
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Gustaaf Willem van Imhoff, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius, Maurits van Aerden",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Gustaaf Willem van Imhoff, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius, Maurits van Aerden, Jacob Lakeman",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Herman van Suchtelen, Pieter Duquesne, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius, Maurits van Aerden",
      1
     ],
     [
      "Adriaan Valckenier, Joan Paul Schaghen, Joannes Thedens, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius, Maurits van Aerden",
      2
     ],
     [
      "Anthonio Hurdt, Joannes Camphuys, Marten Pit, Nicolaas Schaghen, Joan van Hoorn",
      2
     ],
     [
      "Antonio van Diemen",
      1
     ],
     [
      "Antonio van Diemen, Anthonio Caen, Cornelis van der Lijn",
      3
     ],
     [
      "Antonio van Diemen, Anthonio Caen, Cornelis van der Lijn, Joan Maetsuycker, Justus Schouten, Salomon Sweers",
      1
     ],
     [
      "Antonio van Diemen, Anthonio Caen, Cornelis van der Lijn, Joan Maetsuycker, Justus Schouten, Salomon Sweers, Cornelis Witsen",
      2
     ],
     [
      "Antonio van Diemen, Cornelis van der Lijn",
      3
     ],
     [
      "Antonio van Diemen, Cornelis van der Lijn, Joan Maetsuycker, François Caron, Justus Schouten",
      1
     ],
     [
      "Antonio van Diemen, Cornelis van der Lijn, Joan Maetsuycker, François Caron, Justus Schouten, Salomon Sweers",
      2
     ],
     [
      "Antonio van Diemen, Cornelis van der Lijn, Joan Maetsuycker, Justus Schouten, Salomon Sweers",
      7
     ],
     [
      "Antonio van Diemen, Cornelis van der Lijn, Johan van Twist",
      1
     ],
     [
      "Antonio van Diemen, Cornelis van der Lijn, Salomon Sweers, Paulus Croocq, Simon van Alphen",
      1
     ],
     [
      "Antonio van Diemen, Cornelis van der Lijn, Salomon Sweers, Simon van Alphen",
      2
     ],
     [
      "Antonio van Diemen, Philips Lucasz, Antonio Caen",
      1
     ],
     [
      "Antonio van Diemen, Philips Lucasz, Artus Gijsels, Antonio Caen",
      1
     ],
     [
      "Antonio van Diemen, Philips Lucasz, Artus Gijsels, Hans Putmans, Antonio Caen, Joan Ottens",
      1
     ],
     [
      "Antonio van Diemen, Philips Lucasz, Artus Gijsels, Jan van der Burch",
      1
     ],
     [
      "Antonio van Diemen, Philips Lucasz, Carel Reniers, Abraham Welsing, Cornelis van der Lijn",
      3
     ],
     [
      "Carel Reniers, Joan Maetsuycker, Carel Hartsinck, Joan Cunaeus, Cornelis Caesar, Dirck Jansz Steur",
      2
     ],
     [
      "Carel Reniers, Joan Maetsuycker, Gerard Demmer, Carel Hartsinck, Aernout de Vlaming van Oudtshoorn, Cornelis Caesar, Willem Versteghen",
      2
     ],
     [
      "Carel Reniers, Joan Maetsuycker, Gerard Demmer, Carel Hartsinck, Aernout de Vlaming van Oudtshoorn, Jan van Teylingen, Cornelis Caesar",
      1
     ],
     [
      "Carel Reniers, Joan Maetsuycker, Gerard Demmer, Joan Cunaeus, Arnold de Vlaming van Oudtshoorn, Arnold Heussen, Willem van der Beecken",
      1
     ],
     [
      "Carel Reniers, Joan Maetsuycker, Gerard Demmer, Joan Cunaeus, Willem Versteghen, Jacob de With, Dirck Jansz Steur",
      2
     ],
     [
      "Christoffel van Swoll, Abraham Douglas, Cornelis Chasteleyn, Mattheus de Haan, Frans Castelyn, Laurens Tolling, Hendrik Zwaardecroon, Pieter Rooselaar, Theodorus de Haeze, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      3
     ],
     [
      "Christoffel van Swoll, Abraham Douglas, Mattheus de Haan, Frans Castelyn, Hendrik Zwaardecroon, Theodorus de Haeze, Laurens Tolling, Pieter Rooselaar, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing, Ferdinand de Groot",
      1
     ],
     [
      "Christoffel van Swoll, Abraham Douglas, Mattheus de Haan, Frans Castelyn, Laurens Tolling, Hendrik Zwaardecroon, Pieter Rooselaar, Theodorus de Haeze, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing",
      3
     ],
     [
      "Christoffel van Swoll, Frans Castelyn, Mattheus de Haan, Hendrik Zwaardecroon, Samuel Timmerman, Theodorus de Haeze, Jacob Faes, Laurens Tolling, Joan Cornelis d'Ableing, Ferdinand de Groot, Willem Six, Cornelis Hasselaar",
      1
     ],
     [
      "Christoffel van Swoll, Frans Castelyn, Mattheus de Haan, Hendrik Zwaardecroon, Theodorus de Haeze, Laurens Tolling, Pieter Rooselaar, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing, Ferdinand de Groot",
      2
     ],
     [
      "Christoffel van Swoll, Frans Castelyn, Mattheus de Haan, Hendrik Zwaardecroon, Theodorus de Haeze, Laurens Tolling, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing, Ferdinand de Groot",
      1
     ],
     [
      "Christoffel van Swoll, Frans Castelyn, Mattheus de Haan, Hendrik Zwaardecroon, Theodorus de Haeze, Samuel Timmerman, Jacob Faes, Laurens Tolling, Joan Cornelis d'Ableing, Ferdinand de Groot, Willem Six",
      4
     ],
     [
      "Christoffel van Swoll, Frans Castelyn, Mattheus de Haan, Hendrik Zwaardecroon, Theodorus de Haeze, Samuel Timmerman, Jacob Faes, Laurens Tolling, Joan Cornelis d'Ableing, Ferdinand de Groot, Willem Six, Cornelis Hasselaar",
      2
     ],
     [
      "Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Willem van Outhoorn, Joan van Hoorn",
      1
     ],
     [
      "Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Willem van Outhoorn, Joannes Camphuys, Frederik Bent",
      4
     ],
     [
      "Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Willem van Outhoorn, Joannes Camphuys, Marten Pit, Nicolaas Schaghen, Joan van Hoorn",
      1
     ],
     [
      "Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Willem van Outhoorn, Joannes Camphuys, Nicolaas Schaghen, Joan van Hoorn",
      2
     ],
     [
      "Cornelis van der Lijn, François Caron, Carel Reniers, Anthonio Caen",
      1
     ],
     [
      "Cornelis van der Lijn, François Caron, Carel Reniers, Anthonio Caen, Jochem Roelofsz van Dutecum",
      2
     ],
     [
      "Cornelis van der Lijn, François Caron, Carel Reniers, Anthonio Caen, Jochem Roelofsz van Dutecum, Gerard Demmer, Wollebrant Geleynsz de Jongh",
      1
     ],
     [
      "Cornelis van der Lijn, François Caron, Carel Reniers, Gerard Demmer",
      1
     ],
     [
      "Cornelis van der Lijn, François Caron, Carel Reniers, Gerard Demmer, Arent Barendsz",
      1
     ],
     [
      "Cornelis van der Lijn, François Caron, Carel Reniers, Jochem Roelofsz van Dutecum, Gerard Demmer",
      2
     ],
     [
      "Cornelis van der Lijn, Joan Maetsuycker, Carel Reniers, Simon van Alphen",
      2
     ],
     [
      "Cornelis van der Lijn, Joan Maetsuycker, Simon van Alphen",
      1
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Dirk van Cloon, Jacob Christiaan Pielat, Joan Paul Schaghen",
      2
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Dirk van Cloon, Jacob Christiaan Pielat, Joan Paul Schaghen, Daniël van der Maas",
      1
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Valckenier, Dirk van Cloon, Jacob Christiaan Pielat, Joan Paul Schaghen",
      1
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen, Adriaan Oostwalt, Adriaan Valckenier, Dirk van Cloon, Wouter Hendrix",
      1
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen, Herman van Bayen, Adriaan Oostwalt",
      9
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Dirk van Cloon, Wouter Hendrix",
      3
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen, Herman van Bayen, Adriaan Valckenier, Dirk van Cloon, Wouter Hendrix",
      1
     ],
     [
      "Diderik Durven, Cornelis Hasselaar, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Dirk van Cloon, Jacob Christiaan Pielat, Joan Paul Schaghen",
      1
     ],
     [
      "Dirk van Cloon, Joan Everard van der Schuer, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Josua van Arrewijne, Joannes Bernard",
      1
     ],
     [
      "Dirk van Cloon, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Gustaaf Willem van Imhoff, Josua van Arrewijne",
      1
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen",
      1
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Herman van Bayen, Adriaan Valckenier, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen",
      1
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Jacob Christiaan Pielat, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Josua van Arrewijne",
      1
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Joan Paul Schaghen, Abraham Patras, Joannes Thedens",
      1
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett",
      4
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Joan Everard van der Schuer, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett",
      2
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Jacob Christiaan Pielat, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff, Elias de Haeze, Isaac van Schinne, Herman van Suchtelen",
      1
     ],
     [
      "Dirk van Cloon, Wijbrant Blom, Michiel Westpalm, Joan François de Witte, Van Schooten, Herman van Bayen, Adriaan Oostwalt, Adriaan Valckenier, Jacob Christiaan Pielat, Joan Paul Schaghen, Abraham Patras, Joannes Thedens, Frederik Julius Coyett, Gustaaf Willem van Imhoff",
      1
     ],
     [
      "Gerard Reynst",
      3
     ],
     [
      "Gouverneur-generaal, Raden",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Daniël Nolthenius, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Johan Herman Theling",
      2
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Jan Huyghens",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Jacob van der Waeyen, Petrus Albertus van der Parra",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Jacob van der Waeyen, Petrus Albertus van der Parra, Galenus Mersen, Jurgen van der Spar",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob Mossel, Arend van Broyel, Jacob van der Waeyen, Jurgen van der Spar, Jan Huyghens",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob Mossel, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob Mossel, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Jan Huyghens",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Arend van Broyel, Hugo Verijssel",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jacob Mossel, Arend van Broyel, Hugo Verijssel",
      4
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Jacob van der Waeyen, Petrus Albertus van der Parra",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Jacob van der Waeyen, Petrus Albertus van der Parra, Galenus Mersen",
      4
     ],
     [
      "Gustaaf Willem van Imhoff, Nicolaas Crul, Daniël Nolthenius, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Johan Herman Theling",
      2
     ],
     [
      "Gustaaf Willem van Imhoff, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Daniël Overbeek, Jacob van den Bosch, Gijsbertus Schuylenburg, Jacob Mossel, Arend van Broyel",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Gijsbertus Schuylenburg, Jacob Mossel, Arend van Broyel",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Johan Herman Theling",
      3
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Jacob Lakeman",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Jacob Lakeman, Joannes Mattheus Cluysenaar",
      4
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Jacob Lakeman, Joannes Mattheus Cluysenaar, Daniël Overbeek, Gijsbertus Schuylenburg, Jacob Mossel",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Jacob Lakeman, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Gijsbertus Schuylenburg, Jacob Mossel",
      2
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Jacob Lakeman, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jan Albert Sichterman, Gijsbertus Schuylenburg, Jacob Mossel",
      2
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Gijsbertus Schuylenburg, Jacob Mossel",
      1
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Gijsbertus Schuylenburg, Jacob Mossel, Arend van Broyel",
      3
     ],
     [
      "Gustaaf Willem van Imhoff, Pieter Rochus Pasques de Chavonnes, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Joannes Mattheus Cluysenaar, Daniël Overbeek, Jacob van den Bosch, Jacob Mossel, Arend van Broyel, Hugo Verijssel, Johan Herman Theling",
      1
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Jacob Faes, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Diderik Durven, Wijbrant Blom, Petrus Vuyst",
      2
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Jacob Faes, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Hans Frederik Bergman, Diderik Durven, Wijbrant Blom, Petrus Vuyst",
      1
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing, Anthony Huysman, Laurens Tolling, Cornelis Hasselaar, Joan Adriaan Crudop, Diderik Durven",
      2
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing, Anthony Huysman, Laurens Tolling, Cornelis Hasselaar, Joan Adriaan Crudop, Diderik Durven, Wijbrant Blom",
      2
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Samuel Timmerman, Jacob Faes, Joan Cornelis d'Ableing, Anthony Huysman, Laurens Tolling, Joan Adriaan Crudop, Diderik Durven",
      1
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Samuel Timmerman, Jacob Faes, Laurens Tolling, Joan Cornelis d'Ableing, Anthony Huysman",
      1
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Samuel Timmerman, Jacob Faes, Laurens Tolling, Joan Cornelis d'Ableing, Cornelis Hasselaar, Anthony Huysman",
      1
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Samuel Timmerman, Jacob Faes, Laurens Tolling, Joan Cornelis d'Ableing, Ferdinand de Groot, Willem Backer Jacobsz, Cornelis Hasselaar, Anthony Huysman",
      3
     ],
     [
      "Hendrik Zwaardecroon, Frans Castelyn, Mattheus de Haan, Samuel Timmerman, Jacob Faes, Laurens Tolling, Joan Cornelis d'Ableing, Willem Backer Jacobsz, Cornelis Hasselaar, Anthony Huysman",
      1
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Diderik Durven, Wybrand Blom, Petrus Vuyst",
      1
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Diderik Durven, Ewout van Dishoeck, Wijbrant Blom",
      3
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Hans Frederik Bergman, Diderik Durven, Ewout van Dishoeck, Wijbrant Blom",
      3
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Hans Frederik Bergman, Diderik Durven, Ewout van Dishoeck, Wybrand Blom",
      1
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Hans Frederik Bergman, Diderik Durven, Wijbrant Blom",
      1
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Laurens Tolling, Diderik Durven, Ewout van Dishoeck, Wijbrant Blom",
      1
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Laurens Tolling, Diderik Durven, Ewout van Dishoeck, Wijbrant Blom, Joannes Philippus Sipman",
      2
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Laurens Tolling, Diderik Durven, Wijbrant Blom, Joannes Philippus Sipman",
      2
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Laurens Tolling, Diderik Durven, Wijbrant Blom, Petrus Vuyst, Joannes Philippus Sipman",
      1
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Jacob Faes, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Hans Frederik Bergman, Diderik Durven, Wijbrant Blom",
      1
     ],
     [
      "Hendrik Zwaardecroon, Mattheus de Haan, Jacob Faes, Anthony Huysman, Cornelis Hasselaar, Joan Adriaan Crudop, Laurens Tolling, Hans Frederik Bergman, Diderik Durven, Wijbrant Blom, Petrus Vuyst",
      1
     ],
     [
      "Henrick Brouwer",
      2
     ],
     [
      "Henrick Brouwer Dr, Pieter Vlack, Jan van der Burch",
      1
     ],
     [
      "Henrick Brouwer Dr, Pieter Vlack, Maerten Ysbrantsz, Jan van der Burch",
      2
     ],
     [
      "Henrick Brouwer, Antonio van Diemen Dr, Pieter Vlack, Jan van der Burch",
      3
     ],
     [
      "Henrick Brouwer, Antonio van Diemen Dr, Pieter Vlack, Jan van der Burch Mr, Antonio van den Heuvel",
      1
     ],
     [
      "Henrick Brouwer, Antonio van Diemen Dr, Pieter Vlack, Philips Lucasz, Jan van der Burch",
      1
     ],
     [
      "Henrick Brouwer, Antonio van Diemen, Jan van der Burch",
      1
     ],
     [
      "Henrick Brouwer, Antonio van Diemen, Jan van der Burch, Jan van Broeckum",
      1
     ],
     [
      "Henrick Brouwer, Antonio van Diemen, Philips Lucasz, Maerten Ysbrantsz, Artus Gijsels, Jan van der Burch",
      1
     ],
     [
      "Jacob Mossel, Arend van Broyel, Jacob van der Waeyen, Jurgen van der Spar, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel",
      1
     ],
     [
      "Jacob Mossel, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel",
      1
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Jeremias van Riemsdijk, Reynier de Klerk, Jan Elias van Mijlendonk",
      2
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk, Reynier de Klerk, Jan Elias van Mijlendonk",
      3
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman",
      2
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde, Dithard van Rheede, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk",
      1
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Jeremias van Riemsdijk",
      1
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Jeremias van Riemsdijk, Reynier de Klerk",
      1
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk",
      2
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk, Jan Schreuder, Reynier de Klerk",
      4
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk, Reynier de Klerk",
      5
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk, Reynier de Klerk, Joan Gideon Loten",
      1
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk, Adriaan de Nijs, Reynier de Klerk",
      1
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk, Reynier de Klerk",
      1
     ],
     [
      "Jacob Mossel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Pieter van de Velde, Dithard van Rheede, Huijbert Willem van Bazel, Librecht Hooreman, Joan Andreas van Hohendorf, Jeremias van Riemsdijk, Reynier de Klerk, Joan Gideon Loten",
      1
     ],
     [
      "Jacob Mossel, Joannes Mattheus Cluysenaar, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Joan Gideon Loten, Julius Valentijn Steijn van Gollenesse",
      1
     ],
     [
      "Jacob Mossel, Joannes Mattheus Cluysenaar, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Joan Gideon Loten, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde",
      3
     ],
     [
      "Jacob Mossel, Joannes Mattheus Cluysenaar, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde",
      1
     ],
     [
      "Jacob Mossel, Joannes Mattheus Cluysenaar, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel",
      4
     ],
     [
      "Jacob Mossel, Joannes Mattheus Cluysenaar, Daniël Overbeek, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Jan Huyghens, Joan Gideon Loten",
      3
     ],
     [
      "Jacob Mossel, Joannes Mattheus Cluysenaar, Daniël Overbeek, Arend van Broyel, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Joan Gideon Loten",
      2
     ],
     [
      "Jacob Mossel, Joannes Mattheus Cluysenaar, Jacob van der Waeyen, Petrus Albertus van der Parra, Jurgen van der Spar, Joan Gideon Loten, Julius Valentijn Steijn van Gollenesse, Pieter van de Velde, Dithard van Rheede, Adriaan de Nijs, Huijbert Willem van Bazel",
      1
     ],
     [
      "Jacques Specx Dr, Pieter Vlack, Antonio van Diemen, Jan van der Burch",
      1
     ],
     [
      "Jacques Specx Dr, Pieter Vlack, Antonio van Diemen, Pieter Nuyts, Crijn van Raemburch",
      1
     ],
     [
      "Jacques Specx Dr, Pieter Vlack, Jan van der Burch, Arent Gardenijs",
      1
     ],
     [
      "Jan Pietersz Coen",
      3
     ],
     [
      "Jan Pietersz Coen Dr, Martinus Sonck",
      1
     ],
     [
      "Jan Pietersz Coen Dr, Pieter Vlack, Antonio van Diemen",
      3
     ],
     [
      "Jan Pietersz Coen, Frederick de Houtman, Pieter de Carpentier Dr, Martinus Sonck",
      1
     ],
     [
      "Jan Pietersz Coen, Frederick de Houtman, Pieter de Carpentier, Jacob Dedel Dr, Martinus Sonck",
      1
     ],
     [
      "Jan Pietersz Coen, Jacob Dedel",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Jacob Dedel",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Jacob Dedel Dr, Martinus Sonck",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Jacob Dedel, Frederick de Houtman, Willem Jansz",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Jacques Specx, Pieter van Duynen, Antonio van Diemen, Jeremias de Meester",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Jan Dircksz Lam, Willem van Antzen",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Willem Jansz, Jacob Dedel",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Willem van Antzen",
      4
     ],
     [
      "Jan Pietersz Coen, Pieter de Carpentier, Willem van Antzen, Jacques Specx",
      1
     ],
     [
      "Jan Pietersz Coen, Pieter van Duynen, Antonio van Diemen, Jeremias de Meester",
      3
     ],
     [
      "Jan Pietersz Coen, Willem Jansz, Jacques Lefebvre, Jan van Gorcom Dr, Pieter Vlack, Antonio van Diemen, Adriaan Blocq Martensz",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Aernout de Vlaming van Oudtshoorn, Nicolaes Verburch, Dirck Jansz Steur",
      3
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Arnold de Vlaming van Oudtshoorn, Nicolaes Verburch, Dirck Jansz Steur",
      5
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Arnold de Vlaming van Oudtshoorn, Nicolaes Verburch, Dirck Jansz Steur, Pieter Sterthemius",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Arnold de Vlaming van Oudtshoorn, Nicolaes Verburch, Dirk Jansz Steur, Pieter Sterthemius",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Joan Cunaeus, Arnold de Vlaming van Oudtshoorn, Nicolaes Verburch, Dirck Jansz Steur",
      2
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Joan Cunaeus, Arnold de Vlaming van Oudtshoorn, Nicolaes Verburch, Dirck Jansz Steur, Cornelis Caesar",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Joan Cunaeus, Cornelis Caesar, Dirck Jansz Steur",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Joan Cunaeus, Nicolaes Verburch, Dirck Jansz Steur",
      3
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Joan Cunaeus, Nicolaes Verburch, Dirck Steur, Gaspar van den Bogaerde",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Joan Cunaeus, Nicolaes Verburch, Dirck Steur, Gaspar van den Bogaerde, Dircq Sarcerius",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Dirck Jansz Steur",
      2
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Dirck Jansz Steur, Gaspar van den Bogaerde",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Dirck Jansz Steur, Joan Thijsz",
      2
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Dirck Jansz Steur, Laurens Pit, Pieter Anthonisz Overtwater, Joan Thijsz, Adriaen van der Meyde, Pieter van Hoorn",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Laurens Pit, Pieter Anthonisz Overtwater, Joan Thijsz, Pieter van Hoorn, Jacob Cops",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Laurens Pit, Pieter Anthonisz Overtwater, Mattheus van den Brouck, Joan Thijsz, Johan van Dam, Pieter van Hoorn",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Mattheus van den Brouck, Joan Thijsz, Jacob Hustaert, Pieter van Hoorn",
      3
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Mattheus van den Brouck, Joan Thijsz, Johan van Dam",
      1
     ],
     [
      "Joan Maetsuycker, Carel Hartsinck, Nicolaes Verburch, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Mattheus van den Brouck, Joan Thijsz, Pieter van Hoorn, Jacob Cops",
      1
     ],
     [
      "Joan Maetsuycker, Gerard Hulft, Carel Hartsinck, Joan Cunaeus, Aernout de Vlaming van Oudtshoorn, Nicolaes Verburch, Dirck Jansz Steur",
      1
     ],
     [
      "Joan Maetsuycker, Gerard Hulft, Carel Hartsinck, Joan Cunaeus, Nicolaes Verburch, Dirck Steur",
      1
     ],
     [
      "Joan Maetsuycker, Gerard Hulft, Carel Hartsinck, Joan Cunaeus, Nicolaes Verburch, Dirck Steur, Gaspar van den Bogaerde",
      1
     ],
     [
      "Joan Maetsuycker, Gerard Hulft, Carel Hartsinck, Joan Cunaeus, Nicolaes Verburch, Dirck Steur, Willem van der Beecken",
      2
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Pieter van Hoorn",
      14
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Pieter van Hoorn, Jacob Cops, Willem Volger",
      1
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Pieter van Hoorn, Sibrant Abbema",
      4
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Pieter van Hoorn, Willem Volger",
      1
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Mattheus van den Brouck, Joan Thijsz",
      4
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Mattheus van den Brouck, Joan Thijsz, Pieter van Hoorn",
      2
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Mattheus van den Brouck, Pieter van Hoorn",
      1
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Mattheus van den Brouck, Pieter van Hoorn, Constantin Ranst",
      6
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Laurens Pit, Pieter Overtwater, Pieter van Hoorn",
      4
     ],
     [
      "Joan Maetsuycker, Nicolaes Verburch, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Constantin Ranst, Pieter van Hoorn, Sibrant Abbema",
      3
     ],
     [
      "Joan Maetsuycker, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Constantin Ranst, Pieter van Hoorn, Anthonio Paviljoen",
      1
     ],
     [
      "Joan Maetsuycker, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Constantin Ranst, Pieter van Hoorn, Anthonio Paviljoen, Hendrick van Reede",
      1
     ],
     [
      "Joan Maetsuycker, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Constantin Ranst, Pieter van Hoorn, Anthonio Paviljoen, Willem Volger, Hendrick van Reede",
      1
     ],
     [
      "Joan Maetsuycker, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Constantin Ranst, Pieter van Hoorn",
      1
     ],
     [
      "Joan Maetsuycker, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Constantin Ranst, Pieter van Hoorn, Anthonio Paviljoen",
      1
     ],
     [
      "Joan Maetsuycker, Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Cornelis Speelman, Constantin Ranst, Pieter van Hoorn, Sibrant Abbema",
      2
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Abraham Douglas, Pieter de Vos, Adam van Rijn, Bernard Phoonsen, Hendrick Zwaardecroon",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Abraham Douglas, Pieter de Vos, Adam van Rijn, Bernard Phoonsen, Hendrick Zwaardecroon, Cornelis Chasteleyn",
      3
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Abraham Douglas, Pieter de Vos, Adam van Rijn, Cornelis Chasteleyn, Hendrick Zwaardecroon, Mattheus de Haan, Theodorus de Haeze, Laurens Tolling, Frans Castelyn",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Abraham Douglas, Pieter de Vos, Adam van Rijn, Hendrick Zwaardecroon, Cornelis Chasteleyn",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Abraham Douglas, Pieter de Vos, Adam van Rijn, Hendrick Zwaardecroon, Cornelis Chasteleyn, Mattheus de Haan",
      3
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Adam van Rijn, Bernard Phoonsen, Hendrick Zwaardecroon",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Adam van Rijn, Adriaan van der Stel, Hendrik Zwaardecroon, Cornelis Chasteleyn, Mattheus de Haan",
      2
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Pieter de Vos, Adam van Rijn, Bernard Phoonsen, Hendrick Zwaardecroon, Cornelis Chasteleyn",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Pieter de Vos, Bernard Phoonsen, Adam van Rijn, Hendrick Zwaardecroon, Henrick Becker, Cornelis Chasteleyn",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Pieter de Vos, Bernard Phoonsen, Adam van Rijn, Hendrik Zwaardecroon, Henrick Becker, Cornelis Chasteleyn",
      4
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Pieter de Vos, Dirk Comans, Bernard Phoonsen, Adam van Rijn, Hendrik Zwaardecroon, Henrik Becker, Cornelis Chasteleyn, Mattheus de Haan",
      3
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Pieter de Vos, Dirk Comans, Bernard Phoonsen, Hendrik Zwaardecroon, Cornelis Chasteleyn, Mattheus de Haan",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Christoffel van Swoll, Abraham Douglas, Pieter de Vos, Adam van Rijn, Adriaan van der Stel, Hendrik Zwaardecroon, Cornelis Chasteleyn, Willem de Roo, Mattheus de Haan",
      1
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Joannes Cops, Manuel Bornezee, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Adam van Rijn, Adriaan van der Stel, Hendrick Zwaardecroon, Mattheus de Haan",
      2
     ],
     [
      "Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Joannes Cops, Manuel Bornezee, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Adam van Rijn, Adriaan van der Stel, Hendrik Zwaardecroon, Mattheus de Haan",
      5
     ],
     [
      "Joan van Hoorn, Raden van Indië",
      1
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Cornelis van Quaelbergh",
      1
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Cornelis van Quaelbergh, Joan van Hoorn",
      2
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Jacob Pits, Joan van Hoorn, Nicolaas Schaghen, Isaac de Saint-martin, Gerard de Beveren, Robert Padtbrugge",
      2
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Jacob Pits, Joan van Hoorn, Nicolaas Schaghen, Isaac de Saint-martin, Robert Padtbrugge",
      1
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Joan van Hoorn",
      1
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Joan van Hoorn, Cornelis van Quaelbergh, Isaac de Saint-martin, Gerard de Beveren",
      1
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Joan van Hoorn, Nicolaas Schaghen, Isaac de Saint-martin, Gerard de Beveren",
      1
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Marten Pit, Nicolaas Schaghen, Joan van Hoorn",
      3
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Ryckloff van Goens, Marten Pit, Cornelis van Quaelbergh, Joan van Hoorn, Isaac de Saint-martin",
      1
     ],
     [
      "Joannes Camphuys, Anthonio Hurdt, Willem van Outhoorn, Ryckloff van Goens, Marten Pit, Cornelis van Quaelbergh, Joan van Hoorn, Isaac de Saint-martin, Thomas Slicher",
      2
     ],
     [
      "Joannes Camphuys, Willem van Outhoorn, Joan van Hoorn, Isaac de Saint-martin, Wouter Valckenier, Abraham van Riebeeck, Manuel Bornezee",
      1
     ],
     [
      "Joannes Camphuys, Willem van Outhoorn, Joan van Hoorn, Wouter Valckenier, Abraham van Riebeeck, Manuel Bornezee",
      2
     ],
     [
      "Joannes Camphuys, Willem van Outhoorn, Marten Pit, Jacob Pits, Joan van Hoorn, Isaac de Saint-martin, Gerard de Beveren",
      1
     ],
     [
      "Joannes Camphuys, Willem van Outhoorn, Marten Pit, Joan van Hoorn, Isaac de Saint-martin, Gerard de Beveren",
      2
     ],
     [
      "Joannes Camphuys, Willem van Outhoorn, Marten Pit, Joan van Hoorn, Isaac de Saint-martin, Gerard de Beveren, Wouter Valckenier",
      3
     ],
     [
      "Joannes Thedens, Daniël Nolthenius, Pieter Rochus Pasques de Chavonnes, Jacob Lakeman, Elias Guillot, Thomas van Spreekens, Nicolaas van Berendregt, Joannes Mattheus Cluysenaar, Maurits van Aerden, Nicolaas Crul",
      2
     ],
     [
      "Joannes Thedens, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden",
      1
     ],
     [
      "Joannes Thedens, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden",
      2
     ],
     [
      "Joannes Thedens, Joan Paul Schaghen, Herman van Suchtelen, Pieter Rochus Pasques de Chavonnes, Pieter Duquesne, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Joannes Macaré, Daniël Nolthenius, Maurits van Aerden",
      1
     ],
     [
      "Joannes Thedens, Pieter Rochus Pasques de Chavonnes, Daniël Nolthenius, Nicolaas van Berendregt, Jacob Lakeman, Thomas van Spreekens, Joannes Mattheus Cluysenaar, Nicolaas Crul",
      1
     ],
     [
      "Joannes Thedens, Pieter Rochus Pasques de Chavonnes, Elias Guillot, Nicolaas van Berendregt, Nicolaas Crul, Daniël Nolthenius, Maurits van Aerden, Jacob Lakeman, Thomas van Spreekens, Joannes Mattheus Cluysenaar",
      1
     ],
     [
      "Laurens Reael",
      11
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wijbrant Blom, Diderik Durven, Joan Everard van der Schuer, Stephanus Versluys, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen, Herman van Bayen",
      6
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wijbrant Blom, Diderik Durven, Petrus Vuyst, Pieter Gabry, Jacob Willem Dubbeldekop, Joan Everard van der Schuer",
      2
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wijbrant Blom, Diderik Durven, Pieter Gabry, Jacob Willem Dubbeldekop, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle",
      2
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wijbrant Blom, Diderik Durven, Pieter Gabry, Jacob Willem Dubbeldekop, Joan Everard van der Schuer, Michiel Westpalm, Henrik van Baerle",
      1
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wijbrant Blom, Diderik Durven, Pieter Gabry, Jacob Willem Dubbeldekop, Joan Everard van der Schuer, Stephanus Versluys, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen",
      2
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wijbrant Blom, Diderik Durven, Pieter Gabry, Joan Everard van der Schuer, Stephanus Versluys, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen",
      1
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wybrand Blom, Diderik Durven, Petrus Vuyst, Pieter Gabry, Jacob Willem Dubbeldekop, Joan Everard van der Schuer",
      2
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wybrand Blom, Diderik Durven, Pieter Gabry, Jacob Willem Dubbeldekop, Joan Everard van der Schuer, Michiel Westpalm, Hendrik van Baerle",
      1
     ],
     [
      "Mattheus de Haan, Anthony Huysman, Cornelis Hasselaar, Wybrand Blom, Diderik Durven, Pieter Gabry, Jacob Willem Dubbeldekop, Joan Everard van der Schuer, Stephanus Versluys, Michiel Westpalm, Hendrik van Baerle, Joan François de Witte, Van Schooten, Rogier Thomas van Heyningen",
      2
     ],
     [
      "Pieter Both",
      22
     ],
     [
      "Pieter de Carpentier",
      1
     ],
     [
      "Pieter de Carpentier, Frederick de Houtman, Jacob Dedel Dr, Martinus Sonck, Jacques Specx",
      1
     ],
     [
      "Pieter de Carpentier, Frederick de Houtman, Jacob Dedel Dr, Martinus Sonck, Jacques Specx, Jan van Gorcom",
      1
     ],
     [
      "Pieter de Carpentier, Jacob Dedel",
      1
     ],
     [
      "Pieter de Carpentier, Jacob Dedel Dr, Martinus Sonck, Jacques Specx, Jan van Gorcom",
      1
     ],
     [
      "Pieter de Carpentier, Jacob Dedel, Cornelis Reyersz, Abraham van Uffelen",
      1
     ],
     [
      "Pieter de Carpentier, Jacques Specx Dr, Pieter Vlack, Antonio van Diemen",
      4
     ],
     [
      "Pieter de Carpentier, Jacques Specx Dr, Pieter Vlack, Antonio van Diemen, Wijbrant Schram",
      1
     ],
     [
      "Pieter de Carpentier, Raden",
      5
     ],
     [
      "Pieter de Carpentier, Wijbrant Schram, Jacques Specx Dr, Pieter Vlack, Antonio van Diemen",
      1
     ],
     [
      "Pieter de Carpentier, Willem Jansz, Jacques Specx",
      1
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Dirck Blom, Joannes Camphuys",
      1
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Dirck Blom, Willem van Outhoorn, Joannes Camphuys",
      4
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Dirck Blom, Willem van Outhoorn, Joannes Camphuys, Frederik Bent",
      1
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Willem van Outhoorn, Frederik Bent",
      1
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Balthasar Bort, Anthonio Hurdt, Willem van Outhoorn, Joannes Camphuys, Frederik Bent",
      6
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Balthasar Bort, Willem van Outhoorn, Joannes Camphuys",
      4
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Willem van Outhoorn, Joannes Camphuys, Jacob Pits",
      1
     ],
     [
      "Ryckloff van Goens, Cornelis Speelman, Willem van Outhoorn, Joannes Camphuys, Jacob Pits, Constantijn Nobel",
      1
     ],
     [
      "Ryckloff van Goens, Laurens Pit, Pieter Overtwater, Pieter van Hoorn, Anthonio Paviljoen",
      2
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Joannes Cops, Manuel Bornezee, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Adam van Rijn, Adriaan van der Stel",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Joannes Cops, Manuel Bornezee, Jacob van Dam, Christoffel van Swoll, Abraham Douglas, Adam van Rijn",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Joannes Cops, Manuel Bornezee, Jacob van Dam, Christoffel van Swoll, Abraham Douglas, Hendrik Joan Winkelman, Adam van Rijn",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Joannes Cops, Manuel Bornezee, Jacob van Dam, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Adam van Rijn, Adriaan van der Stel",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Abraham van Riebeeck, Laurens Pijl, Manuel Bornezee, Christoffel van Swoll, Herman de Wilde, Abraham Douglas, Adam van Rijn, Adriaan van der Stel",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Isaac de Saint-martin, Dirk de Haas, Wouter Valckenier, Abraham van Riebeeck, Manuel Bornezee, Wybrand Lycochthon",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Abraham van Riebeeck, Joannes Cops, Manuel Bornezee, Jacob van Dam, Christoffel van Swoll",
      5
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Abraham van Riebeeck, Joannes Cops, Manuel Bornezee, Jacob van Dam, Christoffel van Swoll, Abraham Douglas",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Dirk de Haas, Abraham van Riebeeck, Joannes Cops, Manuel Bornezee, Laurens Pit, Thomas van Rhee, Jacob van Dam",
      3
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Dirk de Haas, Abraham van Riebeeck, Joannes Cops, Manuel Bornezee, Thomas van Rhee, Jacob van Dam, Christoffel van Swoll",
      6
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Dirk de Haas, Abraham van Riebeeck, Wouter Valckenier, Joannes Cops, Manuel Bornezee, Wybrand Lycochthon, Thomas van Rhee",
      4
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Dirk de Haas, Abraham van Riebeeck, Wouter Valckenier, Joannes Cops, Manuel Bornezee, Wybrand Lycochthon, Thomas van Rhee, Jacob van Dam",
      5
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Dirk de Haas, Abraham van Riebeeck, Wouter Valckenier, Joannes Cops, Manuel Bornezee, Wybrand Lycochthon, Willem van Wijngaerden",
      2
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Dirk de Haas, Wouter Valckenier, Abraham van Riebeeck, Manuel Bornezee, Wybrand Lycochthon",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Isaac de Saint-martin, Dirk de Haas, Abraham van Riebeeck, Joan van Leene, Wouter Valckenier, Manuel Bornezee, Wybrand Lycochthon, Joachim Nieustadt",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Isaac de Saint-martin, Dirk de Haas, Abraham van Riebeeck, Wouter Valckenier, Joan van Leene, Manuel Bornezee, Wybrand Lycochthon, Willem van Wijngaerden",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Isaac de Saint-martin, Dirk de Haas, Abraham van Riebeeck, Wouter Valckenier, Joannes Cops, Manuel Bornezee, Wybrand Lycochthon, Joachim Nieustadt",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Isaac de Saint-martin, Dirk de Haas, Abraham van Riebeeck, Wouter Valckenier, Joannes Cops, Manuel Bornezee, Wybrand Lycochthon, Joachim Nieustadt, Willem van Wijngaerden",
      3
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Isaac de Saint-martin, Dirk de Haas, Abraham van Riebeeck, Wouter Valckenier, Manuel Bornezee, Wybrand Lycochthon, Joachim Nieustadt, Willem van Wijngaerden",
      1
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Isaac de Saint-martin, Dirk de Haas, Jan van Leene, Wouter Valckenier, Abraham van Riebeeck, Manuel Bornezee, Wybrand Lycochthon",
      2
     ],
     [
      "Willem van Outhoorn, Joan van Hoorn, Laurens Pijl, Isaac de Saint-martin, Dirk de Haas, Wouter Valckenier, Abraham van Riebeeck, Manuel Bornezee, Wybrand Lycochthon",
      1
     ]
    ],
    "tip": false,
    "pos": "author",
    "pattern": "",
    "description": "full author names"
   },
   "date": {
    "valueMap": [
     [
      "1610-10-14",
      1
     ],
     [
      "1610-2-25",
      1
     ],
     [
      "1610-8-6",
      1
     ],
     [
      "1611-7-18",
      1
     ],
     [
      "1612-3-31",
      1
     ],
     [
      "1612-7-26",
      7
     ],
     [
      "1614-1-1",
      3
     ],
     [
      "1614-11-10",
      5
     ],
     [
      "1614-11-11",
      1
     ],
     [
      "1615-10-26",
      2
     ],
     [
      "1616-7-18",
      1
     ],
     [
      "1616-9-22",
      1
     ],
     [
      "1617-11-10",
      1
     ],
     [
      "1617-12-17",
      2
     ],
     [
      "1617-5-10",
      1
     ],
     [
      "1617-7-2",
      1
     ],
     [
      "1618-1-6",
      1
     ],
     [
      "1618-5-7",
      1
     ],
     [
      "1618-7-11",
      1
     ],
     [
      "1618-8-20",
      1
     ],
     [
      "1619-10-15",
      1
     ],
     [
      "1619-10-7",
      1
     ],
     [
      "1619-8-5",
      1
     ],
     [
      "1620-1-22",
      1
     ],
     [
      "1620-1-29",
      1
     ],
     [
      "1620-10-26",
      1
     ],
     [
      "1620-5-11",
      1
     ],
     [
      "1620-5-12",
      1
     ],
     [
      "1620-7-31",
      1
     ],
     [
      "1621-1-8",
      1
     ],
     [
      "1621-11-16",
      1
     ],
     [
      "1621-12-20",
      1
     ],
     [
      "1621-3-8",
      1
     ],
     [
      "1621-5-6",
      1
     ],
     [
      "1621-7-9",
      1
     ],
     [
      "1622-1-21",
      1
     ],
     [
      "1622-3-14",
      1
     ],
     [
      "1622-3-26",
      1
     ],
     [
      "1622-9-6",
      1
     ],
     [
      "1623-12-25",
      1
     ],
     [
      "1623-2-1",
      1
     ],
     [
      "1623-2-24",
      1
     ],
     [
      "1624-1-3",
      1
     ],
     [
      "1624-3-4",
      1
     ],
     [
      "1625-1-27",
      1
     ],
     [
      "1625-10-27",
      1
     ],
     [
      "1625-8-13",
      1
     ],
     [
      "1625-9-13",
      1
     ],
     [
      "1626-12-13",
      1
     ],
     [
      "1626-12-15",
      1
     ],
     [
      "1626-12-26",
      1
     ],
     [
      "1626-2-15",
      1
     ],
     [
      "1626-2-3",
      1
     ],
     [
      "1627-11-9",
      1
     ],
     [
      "1627-2-2",
      1
     ],
     [
      "1627-7-29",
      1
     ],
     [
      "1628-1-13",
      1
     ],
     [
      "1628-1-24",
      1
     ],
     [
      "1628-1-6",
      1
     ],
     [
      "1628-11-17",
      1
     ],
     [
      "1628-11-3",
      1
     ],
     [
      "1629-12-15",
      1
     ],
     [
      "1629-2-10",
      1
     ],
     [
      "1629-3-18",
      1
     ],
     [
      "1631-3-7",
      1
     ],
     [
      "1631-6-5",
      1
     ],
     [
      "1632-1-6",
      1
     ],
     [
      "1632-12-1",
      1
     ],
     [
      "1633-12-15",
      1
     ],
     [
      "1633-12-25",
      1
     ],
     [
      "1633-2-7",
      1
     ],
     [
      "1633-2-8",
      1
     ],
     [
      "1633-8-15",
      1
     ],
     [
      "1634-12-27",
      1
     ],
     [
      "1634-2-20",
      1
     ],
     [
      "1634-3-5",
      1
     ],
     [
      "1634-8-15",
      1
     ],
     [
      "1635-1-8",
      1
     ],
     [
      "1635-12-31",
      1
     ],
     [
      "1636-1-4",
      1
     ],
     [
      "1636-12-28",
      1
     ],
     [
      "1636-2-2",
      1
     ],
     [
      "1637-12-26",
      1
     ],
     [
      "1637-12-9",
      1
     ],
     [
      "1638-12-22",
      1
     ],
     [
      "1638-12-30",
      1
     ],
     [
      "1639-1-12",
      1
     ],
     [
      "1639-12-18",
      1
     ],
     [
      "1640-1-31",
      1
     ],
     [
      "1640-1-8",
      1
     ],
     [
      "1640-11-30",
      1
     ],
     [
      "1640-9-9",
      1
     ],
     [
      "1641-1-31",
      1
     ],
     [
      "1641-1-8",
      1
     ],
     [
      "1641-11-16",
      1
     ],
     [
      "1641-12-12",
      1
     ],
     [
      "1641-9-14",
      1
     ],
     [
      "1642-12-12",
      1
     ],
     [
      "1642-12-23",
      1
     ],
     [
      "1643-1-13",
      1
     ],
     [
      "1643-1-23",
      1
     ],
     [
      "1643-12-22",
      1
     ],
     [
      "1643-3-18",
      1
     ],
     [
      "1643-3-7",
      1
     ],
     [
      "1644-1-13",
      1
     ],
     [
      "1644-1-4",
      1
     ],
     [
      "1644-1-9",
      1
     ],
     [
      "1644-12-23",
      1
     ],
     [
      "1645-1-20",
      1
     ],
     [
      "1645-12-17",
      1
     ],
     [
      "1645-12-31",
      1
     ],
     [
      "1645-2-6",
      1
     ],
     [
      "1645-7-9",
      1
     ],
     [
      "1646-12-21",
      1
     ],
     [
      "1647-1-15",
      1
     ],
     [
      "1647-12-31",
      1
     ],
     [
      "1647-4-14",
      1
     ],
     [
      "1649-1-18",
      1
     ],
     [
      "1649-1-26",
      1
     ],
     [
      "1649-12-31",
      1
     ],
     [
      "1650-1-18",
      1
     ],
     [
      "1650-12-10",
      1
     ],
     [
      "1651-1-20",
      1
     ],
     [
      "1651-12-19",
      1
     ],
     [
      "1651-2-10",
      1
     ],
     [
      "1652-1-24",
      1
     ],
     [
      "1652-12-24",
      1
     ],
     [
      "1652-2-5",
      1
     ],
     [
      "1653-1-31",
      2
     ],
     [
      "1654-1-19",
      1
     ],
     [
      "1654-11-7",
      1
     ],
     [
      "1654-2-6",
      1
     ],
     [
      "1655-1-26",
      1
     ],
     [
      "1655-12-24",
      1
     ],
     [
      "1655-2-4",
      1
     ],
     [
      "1655-4-1",
      1
     ],
     [
      "1655-7-12",
      1
     ],
     [
      "1656-12-4",
      1
     ],
     [
      "1656-2-1",
      1
     ],
     [
      "1656-7-18",
      1
     ],
     [
      "1656-7-31",
      1
     ],
     [
      "1657-1-31",
      1
     ],
     [
      "1657-12-17",
      1
     ],
     [
      "1658-1-17",
      1
     ],
     [
      "1658-1-6",
      1
     ],
     [
      "1658-12-14",
      1
     ],
     [
      "1659-12-16",
      1
     ],
     [
      "1660-1-16",
      1
     ],
     [
      "1660-12-16",
      1
     ],
     [
      "1661-1-26",
      1
     ],
     [
      "1661-1-28",
      1
     ],
     [
      "1661-12-22",
      1
     ],
     [
      "1661-7-29",
      1
     ],
     [
      "1662-1-30",
      1
     ],
     [
      "1662-12-26",
      1
     ],
     [
      "1662-4-22",
      1
     ],
     [
      "1663-1-29",
      1
     ],
     [
      "1663-12-21",
      1
     ],
     [
      "1664-1-27",
      1
     ],
     [
      "1664-12-23",
      1
     ],
     [
      "1664-8-4",
      1
     ],
     [
      "1665-1-30",
      1
     ],
     [
      "1665-2-26",
      1
     ],
     [
      "1666-1-30",
      1
     ],
     [
      "1667-1-25",
      1
     ],
     [
      "1667-10-5",
      1
     ],
     [
      "1667-12-23",
      1
     ],
     [
      "1667-12-31",
      1
     ],
     [
      "1667-12-6",
      1
     ],
     [
      "1668-10-18",
      1
     ],
     [
      "1668-12-1",
      1
     ],
     [
      "1668-12-13",
      1
     ],
     [
      "1668-12-19",
      1
     ],
     [
      "1669-1-31",
      1
     ],
     [
      "1669-11-17",
      1
     ],
     [
      "1669-11-30",
      1
     ],
     [
      "1669-12-15",
      1
     ],
     [
      "1669-2-16",
      1
     ],
     [
      "1669-2-18",
      1
     ],
     [
      "1669-2-28",
      1
     ],
     [
      "1670-1-31",
      1
     ],
     [
      "1670-2-11",
      1
     ],
     [
      "1671-11-16",
      1
     ],
     [
      "1671-12-19",
      1
     ],
     [
      "1671-9-2",
      1
     ],
     [
      "1672-1-31",
      1
     ],
     [
      "1672-12-11",
      1
     ],
     [
      "1672-12-13",
      1
     ],
     [
      "1672-2-20",
      1
     ],
     [
      "1672-2-5",
      1
     ],
     [
      "1672-7-31",
      1
     ],
     [
      "1672-8-27",
      1
     ],
     [
      "1672-9-22",
      1
     ],
     [
      "1673-1-31",
      1
     ],
     [
      "1673-11-13",
      1
     ],
     [
      "1673-12-23",
      1
     ],
     [
      "1674-1-31",
      1
     ],
     [
      "1674-10-8",
      1
     ],
     [
      "1674-11-17",
      1
     ],
     [
      "1674-2-22",
      1
     ],
     [
      "1675-1-31",
      1
     ],
     [
      "1675-11-23",
      1
     ],
     [
      "1675-2-28",
      1
     ],
     [
      "1675-8-29",
      1
     ],
     [
      "1675-9-25",
      1
     ],
     [
      "1676-11-28",
      1
     ],
     [
      "1676-2-15",
      1
     ],
     [
      "1676-2-7",
      1
     ],
     [
      "1676-9-30",
      1
     ],
     [
      "1677-11-24",
      1
     ],
     [
      "1677-2-13",
      1
     ],
     [
      "1677-7-5",
      1
     ],
     [
      "1678-1-16",
      1
     ],
     [
      "1678-11-28",
      1
     ],
     [
      "1678-12-21",
      1
     ],
     [
      "1678-2-15",
      1
     ],
     [
      "1678-5-8",
      1
     ],
     [
      "1678-8-3",
      1
     ],
     [
      "1679-10-10",
      1
     ],
     [
      "1679-12-11",
      1
     ],
     [
      "1679-12-14",
      1
     ],
     [
      "1679-2-13",
      1
     ],
     [
      "1679-2-23",
      1
     ],
     [
      "1679-8-1",
      1
     ],
     [
      "1680-10-13",
      1
     ],
     [
      "1680-11-29",
      1
     ],
     [
      "1680-12-31",
      1
     ],
     [
      "1680-3-13",
      1
     ],
     [
      "1681-11-29",
      1
     ],
     [
      "1681-11-4",
      1
     ],
     [
      "1681-12-28",
      1
     ],
     [
      "1681-12-31",
      1
     ],
     [
      "1681-2-13",
      1
     ],
     [
      "1681-4-29",
      1
     ],
     [
      "1681-7-25",
      1
     ],
     [
      "1681-8-30",
      1
     ],
     [
      "1682-1-8",
      1
     ],
     [
      "1682-10-5",
      1
     ],
     [
      "1682-11-12",
      1
     ],
     [
      "1683-12-24",
      1
     ],
     [
      "1683-12-31",
      1
     ],
     [
      "1683-3-1",
      1
     ],
     [
      "1683-3-19",
      1
     ],
     [
      "1684-1-3",
      1
     ],
     [
      "1684-11-30",
      1
     ],
     [
      "1684-2-19",
      2
     ],
     [
      "1684-5-31",
      1
     ],
     [
      "1685-12-11",
      1
     ],
     [
      "1685-2-12",
      1
     ],
     [
      "1685-2-19",
      1
     ],
     [
      "1685-3-18",
      1
     ],
     [
      "1686-1-8",
      1
     ],
     [
      "1686-12-13",
      1
     ],
     [
      "1686-3-8",
      1
     ],
     [
      "1687-12-23",
      1
     ],
     [
      "1687-2-28",
      1
     ],
     [
      "1688-1-10",
      1
     ],
     [
      "1688-12-27",
      1
     ],
     [
      "1688-3-13",
      1
     ],
     [
      "1689-11-30",
      1
     ],
     [
      "1689-12-30",
      1
     ],
     [
      "1689-2-27",
      1
     ],
     [
      "1689-3-31",
      1
     ],
     [
      "1690-12-10",
      1
     ],
     [
      "1690-3-14",
      1
     ],
     [
      "1691-3-26",
      1
     ],
     [
      "1691-4-17",
      1
     ],
     [
      "1692-1-31",
      1
     ],
     [
      "1692-12-11",
      1
     ],
     [
      "1692-3-24",
      1
     ],
     [
      "1692-3-26",
      1
     ],
     [
      "1693-12-8",
      1
     ],
     [
      "1693-2-9",
      1
     ],
     [
      "1693-3-14",
      1
     ],
     [
      "1694-11-30",
      1
     ],
     [
      "1694-2-6",
      1
     ],
     [
      "1695-11-3",
      1
     ],
     [
      "1695-2-4",
      1
     ],
     [
      "1696-2-8",
      1
     ],
     [
      "1697-1-19",
      1
     ],
     [
      "1697-11-30",
      1
     ],
     [
      "1697-2-19",
      1
     ],
     [
      "1698-12-6",
      1
     ],
     [
      "1698-2-2",
      1
     ],
     [
      "1698-2-21",
      1
     ],
     [
      "1699-1-20",
      1
     ],
     [
      "1699-11-23",
      1
     ],
     [
      "1699-2-10",
      1
     ],
     [
      "1699-3-2",
      1
     ],
     [
      "1699-4-20",
      1
     ],
     [
      "1700-1-20",
      1
     ],
     [
      "1700-10-26",
      1
     ],
     [
      "1700-11-10",
      1
     ],
     [
      "1700-12-1",
      1
     ],
     [
      "1700-12-22",
      1
     ],
     [
      "1700-2-16",
      1
     ],
     [
      "1700-2-19",
      1
     ],
     [
      "1701-1-28",
      1
     ],
     [
      "1701-11-26",
      1
     ],
     [
      "1701-12-31",
      1
     ],
     [
      "1701-2-17",
      1
     ],
     [
      "1702-1-31",
      1
     ],
     [
      "1702-11-30",
      1
     ],
     [
      "1702-8-4",
      1
     ],
     [
      "1703-12-1",
      1
     ],
     [
      "1703-2-25",
      1
     ],
     [
      "1703-9-4",
      1
     ],
     [
      "1704-11-30",
      1
     ],
     [
      "1704-12-18",
      1
     ],
     [
      "1704-2-1",
      1
     ],
     [
      "1704-2-26",
      1
     ],
     [
      "1704-3-14",
      1
     ],
     [
      "1704-8-29",
      1
     ],
     [
      "1705-1-31",
      1
     ],
     [
      "1705-11-30",
      2
     ],
     [
      "1705-2-17",
      1
     ],
     [
      "1705-3-6",
      1
     ],
     [
      "1705-5-10",
      1
     ],
     [
      "1705-8-24",
      1
     ],
     [
      "1706-1-25",
      2
     ],
     [
      "1706-11-30",
      1
     ],
     [
      "1706-12-16",
      1
     ],
     [
      "1706-2-12",
      1
     ],
     [
      "1706-3-31",
      1
     ],
     [
      "1706-5-16",
      1
     ],
     [
      "1706-8-5",
      1
     ],
     [
      "1707-1-15",
      1
     ],
     [
      "1707-11-30",
      1
     ],
     [
      "1707-11-9",
      1
     ],
     [
      "1707-12-18",
      1
     ],
     [
      "1707-2-15",
      1
     ],
     [
      "1708-1-15",
      1
     ],
     [
      "1708-11-25",
      1
     ],
     [
      "1708-12-31",
      1
     ],
     [
      "1708-2-10",
      1
     ],
     [
      "1708-3-17",
      1
     ],
     [
      "1709-1-15",
      1
     ],
     [
      "1709-10-29",
      1
     ],
     [
      "1709-11-30",
      1
     ],
     [
      "1709-2-18",
      1
     ],
     [
      "1710-1-15",
      1
     ],
     [
      "1710-11-29",
      1
     ],
     [
      "1710-2-19",
      1
     ],
     [
      "1711-1-15",
      1
     ],
     [
      "1711-11-30",
      1
     ],
     [
      "1711-2-18",
      1
     ],
     [
      "1712-1-15",
      1
     ],
     [
      "1712-11-25",
      1
     ],
     [
      "1712-2-12",
      1
     ],
     [
      "1713-1-13",
      1
     ],
     [
      "1713-11-20",
      1
     ],
     [
      "1713-2-11",
      1
     ],
     [
      "1714-1-11",
      1
     ],
     [
      "1714-11-26",
      1
     ],
     [
      "1714-2-26",
      1
     ],
     [
      "1715-1-14",
      1
     ],
     [
      "1715-11-28",
      1
     ],
     [
      "1715-2-18",
      1
     ],
     [
      "1715-9-13",
      1
     ],
     [
      "1716-1-15",
      1
     ],
     [
      "1716-11-30",
      1
     ],
     [
      "1716-2-19",
      1
     ],
     [
      "1716-9-18",
      1
     ],
     [
      "1717-1-15",
      1
     ],
     [
      "1717-11-30",
      1
     ],
     [
      "1717-3-23",
      1
     ],
     [
      "1718-1-15",
      1
     ],
     [
      "1718-12-6",
      1
     ],
     [
      "1718-3-20",
      1
     ],
     [
      "1719-1-15",
      1
     ],
     [
      "1719-11-30",
      1
     ],
     [
      "1719-3-28",
      1
     ],
     [
      "1720-1-15",
      1
     ],
     [
      "1720-10-29",
      1
     ],
     [
      "1720-11-30",
      1
     ],
     [
      "1720-3-26",
      1
     ],
     [
      "1721-1-15",
      1
     ],
     [
      "1721-11-30",
      1
     ],
     [
      "1721-2-4",
      1
     ],
     [
      "1721-3-31",
      1
     ],
     [
      "1721-9-19",
      1
     ],
     [
      "1722-1-20",
      1
     ],
     [
      "1722-11-30",
      1
     ],
     [
      "1722-3-31",
      1
     ],
     [
      "1722-9-25",
      1
     ],
     [
      "1723-1-19",
      1
     ],
     [
      "1723-10-15",
      1
     ],
     [
      "1723-12-3",
      1
     ],
     [
      "1723-3-19",
      1
     ],
     [
      "1723-9-21",
      1
     ],
     [
      "1724-1-19",
      1
     ],
     [
      "1724-11-30",
      1
     ],
     [
      "1724-12-14",
      1
     ],
     [
      "1724-12-4",
      1
     ],
     [
      "1724-3-28",
      1
     ],
     [
      "1724-4-2",
      1
     ],
     [
      "1724-9-26",
      1
     ],
     [
      "1725-1-30",
      1
     ],
     [
      "1725-10-22",
      1
     ],
     [
      "1725-11-30",
      1
     ],
     [
      "1725-3-26",
      1
     ],
     [
      "1726-1-26",
      1
     ],
     [
      "1726-10-21",
      1
     ],
     [
      "1726-12-5",
      1
     ],
     [
      "1726-3-27",
      1
     ],
     [
      "1727-1-31",
      1
     ],
     [
      "1727-10-27",
      2
     ],
     [
      "1727-11-30",
      1
     ],
     [
      "1727-3-31",
      1
     ],
     [
      "1728-1-31",
      1
     ],
     [
      "1728-10-31",
      1
     ],
     [
      "1728-12-8",
      2
     ],
     [
      "1728-3-31",
      1
     ],
     [
      "1729-1-31",
      1
     ],
     [
      "1729-11-30",
      1
     ],
     [
      "1729-11-7",
      1
     ],
     [
      "1729-2-25",
      1
     ],
     [
      "1729-3-29",
      1
     ],
     [
      "1729-7-18",
      1
     ],
     [
      "1729-9-30",
      2
     ],
     [
      "1730-1-31",
      1
     ],
     [
      "1730-10-17",
      2
     ],
     [
      "1730-11-30",
      1
     ],
     [
      "1730-2-27",
      1
     ],
     [
      "1730-3-23",
      1
     ],
     [
      "1731-10-12",
      1
     ],
     [
      "1731-12-28",
      1
     ],
     [
      "1731-2-2",
      1
     ],
     [
      "1731-3-31",
      1
     ],
     [
      "1732-10-25",
      1
     ],
     [
      "1732-12-8",
      3
     ],
     [
      "1732-2-14",
      2
     ],
     [
      "1732-3-25",
      1
     ],
     [
      "1733-10-31",
      1
     ],
     [
      "1733-12-22",
      1
     ],
     [
      "1733-2-10",
      1
     ],
     [
      "1733-3-31",
      2
     ],
     [
      "1734-10-6",
      1
     ],
     [
      "1734-11-30",
      1
     ],
     [
      "1734-3-31",
      1
     ],
     [
      "1734-3-7",
      1
     ],
     [
      "1735-1-1",
      1
     ],
     [
      "1735-10-12",
      1
     ],
     [
      "1735-12-16",
      1
     ],
     [
      "1735-3-31",
      1
     ],
     [
      "1736-1-23",
      1
     ],
     [
      "1736-10-24",
      1
     ],
     [
      "1736-12-31",
      1
     ],
     [
      "1736-4-6",
      1
     ],
     [
      "1737-11-28",
      1
     ],
     [
      "1737-2-5",
      1
     ],
     [
      "1737-4-2",
      2
     ],
     [
      "1738-1-25",
      2
     ],
     [
      "1738-11-10",
      1
     ],
     [
      "1738-3-31",
      1
     ],
     [
      "1739-1-31",
      1
     ],
     [
      "1739-12-12",
      2
     ],
     [
      "1739-4-5",
      1
     ],
     [
      "1740-1-12",
      1
     ],
     [
      "1740-10-31",
      1
     ],
     [
      "1740-12-1",
      1
     ],
     [
      "1740-3-31",
      1
     ],
     [
      "1741-1-10",
      1
     ],
     [
      "1741-11-6",
      1
     ],
     [
      "1741-12-6",
      1
     ],
     [
      "1741-3-25",
      1
     ],
     [
      "1742-1-14",
      1
     ],
     [
      "1742-12-17",
      1
     ],
     [
      "1742-12-5",
      1
     ],
     [
      "1742-2-10",
      1
     ],
     [
      "1742-4-5",
      1
     ],
     [
      "1743-1-11",
      1
     ],
     [
      "1743-10-15",
      1
     ],
     [
      "1743-11-5",
      2
     ],
     [
      "1743-12-31",
      1
     ],
     [
      "1743-4-5",
      1
     ],
     [
      "1743-7-3",
      1
     ],
     [
      "1744-10-26",
      1
     ],
     [
      "1744-10-8",
      1
     ],
     [
      "1744-11-3",
      1
     ],
     [
      "1744-12-31",
      1
     ],
     [
      "1745-10-20",
      1
     ],
     [
      "1745-11-12",
      1
     ],
     [
      "1745-12-31",
      1
     ],
     [
      "1745-3-10",
      1
     ],
     [
      "1746-1-28",
      1
     ],
     [
      "1746-10-12",
      1
     ],
     [
      "1746-11-25",
      2
     ],
     [
      "1746-12-31",
      1
     ],
     [
      "1746-3-15",
      2
     ],
     [
      "1747-10-20",
      1
     ],
     [
      "1747-12-31",
      1
     ],
     [
      "1747-3-31",
      2
     ],
     [
      "1747-9-29",
      1
     ],
     [
      "1748-1-13",
      1
     ],
     [
      "1748-1-23",
      1
     ],
     [
      "1748-10-31",
      1
     ],
     [
      "1748-12-31",
      1
     ],
     [
      "1748-3-30",
      1
     ],
     [
      "1748-5-25",
      1
     ],
     [
      "1749-10-17",
      1
     ],
     [
      "1749-11-14",
      1
     ],
     [
      "1749-12-31",
      1
     ],
     [
      "1749-4-30",
      1
     ],
     [
      "1749-9-22",
      1
     ],
     [
      "1750-12-1",
      1
     ],
     [
      "1750-12-31",
      1
     ],
     [
      "1750-3-5",
      1
     ],
     [
      "1750-4-14",
      1
     ],
     [
      "1750-9-29",
      2
     ],
     [
      "1750-9-4",
      1
     ],
     [
      "1751-1-21",
      1
     ],
     [
      "1751-12-31",
      2
     ],
     [
      "1751-4-8",
      2
     ],
     [
      "1751-9-24",
      1
     ],
     [
      "1752-1-18",
      1
     ],
     [
      "1752-10-10",
      1
     ],
     [
      "1752-10-5",
      1
     ],
     [
      "1752-12-30",
      1
     ],
     [
      "1752-12-31",
      1
     ],
     [
      "1752-3-31",
      1
     ],
     [
      "1752-6-6",
      1
     ],
     [
      "1753-10-1",
      1
     ],
     [
      "1753-12-31",
      2
     ],
     [
      "1753-8-13",
      1
     ],
     [
      "1754-10-15",
      1
     ],
     [
      "1754-12-31",
      2
     ],
     [
      "1755-1-15",
      1
     ],
     [
      "1755-10-15",
      1
     ],
     [
      "1755-12-31",
      2
     ],
     [
      "1756-10-15",
      1
     ],
     [
      "1756-12-31",
      1
     ],
     [
      "1756-4-13",
      1
     ],
     [
      "1757-10-15",
      1
     ],
     [
      "1757-12-31",
      1
     ],
     [
      "1757-4-25",
      1
     ],
     [
      "1758-10-15",
      1
     ],
     [
      "1758-12-31",
      1
     ],
     [
      "1758-4-25",
      1
     ],
     [
      "1759-10-15",
      1
     ],
     [
      "1759-12-31",
      1
     ],
     [
      "1759-4-30",
      1
     ],
     [
      "1760-10-15",
      1
     ],
     [
      "1760-12-31",
      1
     ],
     [
      "1760-4-25",
      1
     ],
     [
      "1761-4-25",
      1
     ],
     [
      "1761-4-29",
      1
     ],
     [
      "None-None-None",
      3
     ]
    ],
    "tip": false,
    "pos": "date",
    "pattern": "",
    "description": "date as yyyy-mm-dd"
   },
   "place": {
    "valueMap": [
     [
      "Amboina",
      1
     ],
     [
      "Banda-Neira",
      1
     ],
     [
      "Bantam",
      14
     ],
     [
      "Batavia",
      537
     ],
     [
      "Fort Mauritius nabij Ngofakiaha op het eiland Makéan",
      7
     ],
     [
      "Jakatra",
      1
     ],
     [
      "Kasteel Jakatra",
      12
     ],
     [
      "Kasteel Mauritius nabij Ngofakiaha op Makéan",
      1
     ],
     [
      "Kasteel Nassau op Banda-Neira",
      2
     ],
     [
      "Schip Nieuw Hollandia ter Rede van Banda-Neira ",
      1
     ],
     [
      "Ternate",
      2
     ],
     [
      "Wapen van Amsterdam voor Banda-Neira",
      1
     ],
     [
      "aan boord van de Utrecht nabij de Vlakke Hoek",
      1
     ],
     [
      "aan boord van de Vere voor Maleyo",
      1
     ],
     [
      "aan boord van de Wesel in Straat Sunda",
      1
     ],
     [
      "aan boord van het Wapen van Amsterdam liggende in de Tafelbaai",
      1
     ],
     [
      "aan boord van het Wapen van Amsterdam ter Rede van Mauritius",
      1
     ],
     [
      "aan boord van het Wapen van Amsterdam voor Ile de Mayo",
      1
     ],
     [
      "in het Schip Deventer nabij de zuidpunt van Afrika",
      1
     ]
    ],
    "tip": false,
    "pos": "place",
    "pattern": "",
    "description": "place indication"
   }
  },
  "volume": {
   "number": {
    "valueMap": [
     [
      1,
      1
     ],
     [
      2,
      1
     ],
     [
      3,
      1
     ],
     [
      4,
      1
     ],
     [
      5,
      1
     ],
     [
      6,
      1
     ],
     [
      7,
      1
     ],
     [
      8,
      1
     ],
     [
      9,
      1
     ],
     [
      10,
      1
     ],
     [
      11,
      1
     ],
     [
      12,
      1
     ],
     [
      13,
      1
     ]
    ],
    "tip": false,
    "pos": "number",
    "pattern": "",
    "description": "volume number"
   }
  }
 }
}